version: '3'
services:
    redis:
        image: redis:alpine
        volumes:
            - ./data/redis:/data
    php:
        image: stcer/php:7.2-fpm
        volumes:
            - ../:/var/www/html
